sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26


before_install:
- chmod +x gradlew

script:
- ./gradlew assembleDebug >>/dev/null 2>>/dev/null
- cd app/build/outputs/apk/debug
- ls
